#!/bin/sh

BASEPATH=$(realpath $0)
BASEPATH=$(dirname ${BASEPATH})

echo "#pragma once"

for file in ${BASEPATH}/*.c
do
    cc -o /dev/null -c "${file}" && \
        echo "#define $(basename ${file%.c})"
done
